//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public int MailSettingsID { get; set; }
        public string Sender_Info { get; set; }
        public string Smtp_server { get; set; }
        public string Smpt_port { get; set; }
        public string Mail_Sender { get; set; }
        public string Mail_Email { get; set; }
        public string Mail_Email_Password { get; set; }
    }
}
