//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipAgreement
    {
        public int MembershipAgreementID { get; set; }
        public string MembershipAgreementContent { get; set; }
        public string MembershipAgreementTitle { get; set; }
        public string Member_Keyword { get; set; }
        public string Member_Topic { get; set; }
    }
}
