//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivacyPolicy
    {
        public int PrivacyPolicyID { get; set; }
        public string PrivacyPolicyTitle { get; set; }
        public string Privacy_Keyword { get; set; }
        public string PrivacyPolicyContent { get; set; }
        public string Privacy_Topic { get; set; }
    }
}
