//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seos
    {
        public int SeosID { get; set; }
        public string SeosTitle { get; set; }
        public string Seos_Topic { get; set; }
        public string SeosMap { get; set; }
        public string Seos_Keyword { get; set; }
    }
}
