//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUs
    {
        public int AboutUsID { get; set; }
        public string AboutUsTitle { get; set; }
        public string AboutUsContent { get; set; }
        public string AboutUs_Keyword { get; set; }
        public string AboutUs_Topic { get; set; }
    }
}
