//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
            this.ShoppingCart = new HashSet<ShoppingCart>();
        }
    
        public System.Guid CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string CustomerUserName { get; set; }
        public string Email { get; set; }
        public Nullable<int> CustomerPhoneNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Password { get; set; }
        public Nullable<int> ShoppingCartID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public Nullable<int> OrderHistoryID { get; set; }
        public string DeliveryAddress { get; set; }
        public string BillingAddress { get; set; }
        public Nullable<int> CommentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
    }
}
