//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public System.Guid CustomerID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public string ParcelTracking { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> OrderCargoID { get; set; }
        public Nullable<double> OrderTotalPrice { get; set; }
        public string OrderDeliveryAdress { get; set; }
    
        public virtual CargoCompany CargoCompany { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
