//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopCategory
    {
        public System.Guid TopCategoryID { get; set; }
        public System.Guid CategoryID { get; set; }
        public string TopCategoryName { get; set; }
        public string TopCategoryDetails { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
